name: all-in-one

on:
  workflow_dispatch:
  schedule:
    - cron: 5 */2 * * *
  watch:
    types: started
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo npm install -g typescript
        sudo apt-get install wget
        sudo apt install rename
    - name: down
      run: |
        #echo "========= 开始清空脚本 ========="
        #rm -rf !(utils|docker|backup|redrain)
        echo "========= 开始下载smiek2221的脚本 ========="
        git clone https://github.com/smiek2221/scripts.git  ./smiek2221
        rm -r ./smiek2221/USER_AGENTS.js
        cp -f ./smiek2221/*_*.js ./
        rm -rf ./smiek2221
        echo "========= 开始下载cdle的脚本 ========="
        git clone https://github.com/cdle/jd_study.git  ./cdle
        cp -f ./cdle/*_*.js ./
        rm -rf ./cdle
        echo "========= 开始下载Wenmoux的脚本 ========="
        git clone -b wen https://github.com/Wenmoux/scripts.git ./Wenmoux
        mv ./Wenmoux/jd/chinnkarahoi_jd_bookshop.js ./jd_bookshopWenmoux.js
        cp -f ./Wenmoux/jd/*_*.js ./
        rm -rf ./Wenmoux
        echo "========= 开始下载passby的脚本 ========="
        wget -O ./jd_dj_fruit.js https://github.com/passerby-b/JDDJ/raw/main/jddj_fruit.js
        wget -O ./jd_dj_fruit_collectWater.js https://github.com/passerby-b/JDDJ/raw/main/jddj_fruit_collectWater.js
        wget -O ./jd_dj_bean.js https://github.com/passerby-b/JDDJ/raw/main/jddj_bean.js
        wget -O ./jd_dj_plantBeans.js https://github.com/passerby-b/JDDJ/raw/main/jddj_plantBeans.js
        wget -O ./jd_dj_getPoints.js https://github.com/passerby-b/JDDJ/raw/main/jddj_getPoints.js
        wget -O ./jd_dd_fruit.js https://raw.githubusercontents.com/passerby-b/didi_fruit/main/dd_fruit.js
        wget -O ./jd_ks_fruit.js https://github.com/passerby-b/ks_fruit/raw/main/ks_fruit.js
        echo "========= 开始下载curtinlv的脚本 ========="
        git clone https://github.com/curtinlv/JD-Script.git ./curtinlv
        find ./curtinlv/ -name "*py" -type f -exec cp {} ./ \;
        rm -rf ./curtinlv
        echo "========= 开始下载airacg的脚本及依赖 ========="
        git clone https://github.com/airacg/jd_task.git ./airacg
        cp -r ./airacg/utils ./
        cp -f ./airacg/*_*.js ./
        rm -rf ./airacg
        echo "========= 开始下载单文件脚本 ========="
        #wget -N https://github.com/jiulan/platypus/raw/main/scripts/jd_nzmh.js
        wget -N https://github.com/yangtingxiao/QuantumultX/raw/master/scripts/jd/jd_lotteryMachine.js
        wget -O ./jd_DailyBonus.js https://github.com/NobyDa/Script/raw/master/JD-DailyBonus/JD_DailyBonus.js
        wget -O ./jd_task_pigPet.js https://github.com/airacg/jd_task/raw/main/jr_task_pigPet.js
        wget -O ./jd_shop_sign.js https://github.com/jiulan/platypus/raw/main/scripts/jd_shop_sign.js
        echo "========= 开始备份及合并cron定时文件 ========="
        log_time=$(date "+%Y-%m-%d-%H-%M-%S")
        cp -r ./docker/crontab_list.sh ./backup/cron/crontab_list_$log_time.sh
        cp -r ./.github/workflows/jd_scripts.yml ./backup/yml/jd_scripts_$log_time.yml
        find ./backup/cron/ -type f -mtime +1 -exec rm -f {} \;
        find ./backup/yml/ -type f -mtime +1 -exec rm -f {} \;
        wget -N https://github.com/gossh520/jd-v4/raw/master/docker/crontab_list.sh
        mv -f crontab_list.sh ./docker/crontab_list.sh
        cat ./docker/diy.sh >> ./docker/crontab_list.sh
        echo "========= 开始下载JDHelloWorld的脚本 ========="
        git clone -b main https://github.com/JDHelloWorld/jd_scripts.git ./JDHelloWorld
        mv ./JDHelloWorld/githubAction.md ./githubAction.md
        echo "========= 开始复制依赖 ========="
        cp -f ./JDHelloWorld/package.json ./
        cp -f ./JDHelloWorld/sendNotify.js ./
        cp -f ./JDHelloWorld/jdCookie.js ./
        cp -f ./JDHelloWorld/*ShareCodes.js ./
        echo "========= 开始转换JDHelloWorld的ts脚本 ========="
        cd ./JDHelloWorld
        sudo npm install
        tsc *_*.ts
        echo "========= 开始复制JDHelloWorld的脚本 ========="
        cd ..
        cp -f ./JDHelloWorld/*_*.js ./
        cp -f ./JDHelloWorld/*_*.ts ./backup/ts/
        rm -rf ./JDHelloWorld
        echo "========= 开始更改前缀 ========="
        #for i in `ls | grep -e ^gua`; do mv -f $i `echo "jd_"$i`; done
        rename -f 's/^jr_/jd_/' *
        rename -f 's/^jx_/jd_/' *
        rename -f 's/^gua_/jd_/' *
        #rename -f 's/^jddj/jd_dj_/' *
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am 'update'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: master
